//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use super::sea_orm_active_enums::BookingChangeAction;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "booking_change_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[schema(value_type = String)]
    pub action_time: DateTimeWithTimeZone,
    pub actor_user_id: Option<String>,
    pub action: BookingChangeAction,
    pub reservation_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::notification_log::Entity")]
    NotificationLog,
    #[sea_orm(
        belongs_to = "super::reservation::Entity",
        from = "Column::ReservationId",
        to = "super::reservation::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Reservation,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::ActorUserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    User,
}

impl Related<super::notification_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationLog.def()
    }
}

impl Related<super::reservation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reservation.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
