//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "key_transaction_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub reservation_id: Option<String>,
    pub key_id: Option<String>,
    pub borrowed_to: Option<String>,
    pub handled_by: Option<String>,
    #[schema(value_type = String)]
    pub borrowed_at: DateTimeWithTimeZone,
    #[schema(value_type = Option<String>)]
    pub returned_at: Option<DateTimeWithTimeZone>,
    pub on_time: bool,
    #[schema(value_type = String)]
    pub created_at: DateTimeWithTimeZone,
    #[schema(value_type = String)]
    pub deadline: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::key::Entity",
        from = "Column::KeyId",
        to = "super::key::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Key,
    #[sea_orm(
        belongs_to = "super::reservation::Entity",
        from = "Column::ReservationId",
        to = "super::reservation::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Reservation,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::BorrowedTo",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::HandledBy",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    User1,
}

impl Related<super::key::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Key.def()
    }
}

impl Related<super::reservation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reservation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
