//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub mod prelude;

pub mod announcement;
pub mod black_list;
pub mod classroom;
pub mod infraction;
pub mod key;
pub mod key_transaction_log;
pub mod reservation;
pub mod sea_orm_active_enums;
pub mod user;
