//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "password_reset")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub code: Option<String>,
    #[schema(value_type = Option<String>)]
    pub code_expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub reset_token: Option<String>,
    #[schema(value_type = Option<String>)]
    pub reset_token_expires_at: Option<DateTimeWithTimeZone>,
    #[schema(value_type = Option<String>)]
    pub created_at: DateTimeWithTimeZone,
    #[schema(value_type = Option<String>)]
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
