//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use super::sea_orm_active_enums::ReservationStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "reservation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: Option<String>,
    pub classroom_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub purpose: String,
    #[schema(value_type = String)]
    pub start_time: DateTimeWithTimeZone,
    pub approved_by: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reject_reason: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cancel_reason: Option<String>,
    pub status: ReservationStatus,
    #[schema(value_type = String)]
    pub end_time: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::classroom::Entity",
        from = "Column::ClassroomId",
        to = "super::classroom::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Classroom,
    #[sea_orm(has_many = "super::infraction::Entity")]
    Infraction,
    #[sea_orm(has_many = "super::key_transaction_log::Entity")]
    KeyTransactionLog,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::ApprovedBy",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    User1,
}

impl Related<super::classroom::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Classroom.def()
    }
}

impl Related<super::infraction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Infraction.def()
    }
}

impl Related<super::key_transaction_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KeyTransactionLog.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
